name: Deploy MERN Project with CI/CD

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build React App
        run: |
          sudo apt update
          cd frontend
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: To see the current directory
        run: pwd

      - name: copy the file to ubuntu instance
        uses: nogsantos/scp-deploy@master
        with:
          src: /build/*
          host: ${{ secrets.HOST }}
          remote: /var/www/html
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
            
      - name: Start MERN App with PM2
        run: pm2 start backend/server.js --name "mern-app"

      - name: Install Apache2 (for reverse proxy)
        run: |
          sudo apt update && sudo apt install apache2 -y
          sudo a2enmod proxy proxy_http
          echo '<VirtualHost *:80>
            ServerName mydomain.com
            ProxyPass /api http://localhost:5000/
            ProxyPassReverse /api http://localhost:5000/
            ProxyPass / http://localhost:3000/
            ProxyPassReverse / http://localhost:3000/
            </VirtualHost>' | sudo tee /etc/apache2/sites-available/mern.conf

          sudo a2ensite mern.conf
          sudo systemctl restart apache2

      - name: Save PM2 process for auto-restart
        run: pm2 save
